In [1]:
import numpy as np

In [8]:
# Criando Array 1D.

d1 = np.array([1, 2, 3])
print (d1)

[1 2 3]


In [9]:
# Verificação do tamanho do Array.

d1.shape # Informa que o formato é 3 (representando a quantidade de índices) e nada no final.

(3,)

In [10]:
# Verificação da dimensão do Array.

d1.ndim # Informa que o número de dimensões é 1.

1

In [11]:
# Verificação do tipo do Array.

d1.dtype

dtype('int64')

In [12]:
# Criando Array 2D.

d2 = np.array([[1, 2, 3], [4, 5, 6]])
print (d2)

[[1 2 3]
 [4 5 6]]


In [13]:
# Verificação do tamanho do Array.

d2.shape # Informa que o formato é 2 para 3.

(2, 3)

In [14]:
# Verificação da dimensão do Array.

d2.ndim # Informa que o número de dimensões é 2.

2

In [15]:
# Verificação do tipo do Array.

d1.dtype

dtype('int64')

In [16]:
# Criando Array 3D.

d3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print (d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Verificação do tamanho do Array.

d3.shape # Informa que o formato é de 2 por 2 por 2.

(2, 2, 2)

In [19]:
# Verificação da dimensão do Array.

d3.ndim # Informa que o número de dimensões é 3.

3

In [20]:
# Verificação do tipo do Array.

d3.dtype

dtype('int64')

In [21]:
# Somando duas Arrays.

a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

result = np.add(a, b)
print(result)

[2 4 6]


In [23]:
# Selecionando itens em Arrays:

c = np.array([[2, 3, 4, 5], [6, 7, 8, 9]])
print (c)

[[2 3 4 5]
 [6 7 8 9]]


In [24]:
# Dado o valor do índice da linha e da coluna, retorna o valor contido. array[row, colu]

c[1, 2]

8

In [27]:
# Mostrando apenas uma linha do Array e todas as colunas.

c[0, :]

array([2, 3, 4, 5])

In [28]:
# Mostrando elementos de apenas uma coluna considerando todas as linhas.

c[:, 1]

array([3, 7])